# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e50bb338731f0a06857d584583e8cf7a5f886f465f382ec6ac15ea1d9f6092f2c5d098769a437b0c41e11e416c23cc05faf1db435a54494f9d01896460ba7d6

test:
  secret_key_base: b986e54069d263ab593e0792c24fb6c64625ef49276d9005a6282cbcf4fe4a15571cad1f155ae9c035309ec341ec44d0bf0bb3997fe0a8e29174dda4fb939332

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
